version: '3.8'

services:
  main-db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: vacinacao
    ports:
      - '3806:3306'
    expose:
      - '3306'
    volumes:
        - /data/db:/var/lib/mysql


